#!/usr/bin/env bash

function main {
  set -exfu

  (
    cat /drone/config.yaml.template
    echo
    if [[ -f config.yaml ]]; then
      cat config.yaml
      echo
    fi
    if [[ -n "${PLUGIN_GITHUB_PAGES:-}" ]]; then
      echo uglyurls: false
      echo publishDir: docs
    fi
  ) > /tmp/config.yaml

  if [[ -w . ]]; then
    if [[ -n "${PLUGIN_WATCH:-}" ]]; then
      exec hugo server --bind 0.0.0.0 --disableFastRender --ignoreCache --noHTTPCache --renderToDisk --config /tmp/config.yaml
    else
      exec hugo --config /tmp/config.yaml
    fi
    return $?
  fi

  return 0
}

main "$@"
