#!/usr/bin/env bash

function main {
  set -exfu

  (
    cat /drone/config.yaml.template
    echo
    if [[ -f config.yaml ]]; then
      cat config.yaml
      echo
    fi
    if [[ -n "${PLUGIN_GITHUB_PAGES:-}" ]]; then
      echo uglyurls: false
      echo publishDir: docs
    fi
  ) > /tmp/config.yaml

  if [[ -w . ]]; then
    exec hugo --config /tmp/config.yaml
    return $?
  fi

  return 0
}

main "$@"
